executor: slurm
jobs: 40
use-singularity: True
singularity-args: "--bind ${TMPDIR}:${TMPDIR}"
use-conda: True
keep-going: True
retries: 3
latency-wait: 90
default-resources:
    cpus: 2
    mem_mb: 4000
    runtime: 240
